/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JPanel;
import javax.swing.Timer;




public class ViewQuanLy extends javax.swing.JFrame {

    private JPanel childPanel;

    /**
     * Creates new form mainView
     */
    public ViewQuanLy() {

      initComponents();
        setLocationRelativeTo(null);
        setpanel(new BanHang());
        color();
        JButton[] btn1= {btnBanHang,btnThoat,btnHoaDon,btnKhachHang,btnNhanVien,btnThongKe,btnKhuyenMai};
        JButton[] btn2= {btnBanHang};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(255, 144, 1));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(255, 144, 1));
        }
        
        new Timer(1000, new ActionListener() {
            SimpleDateFormat format = new SimpleDateFormat("HH:mm:ss a");

            @Override
            public void actionPerformed(ActionEvent e) {
                lblDongHo.setText(format.format(new Date()));
            }
        }).start();

    } 
    
    private void setpanel(JPanel panel) {
        childPanel = panel;
        pnmain.removeAll();
        pnmain.add(childPanel);
        pnmain.validate();
    }
    
    
    private void color(){
        JButton[] btns = {btnBanHang,btnThoat,btnHoaDon,btnKhachHang,btnNhanVien,btnSanPham,btnThongKe,btnKhuyenMai};
        for (JButton btn : btns) {
            btn.setBackground(new Color(255, 144, 1));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        pnmain = new javax.swing.JPanel();
        btnThoat = new javax.swing.JButton();
        btnSanPham = new javax.swing.JButton();
        btnKhuyenMai = new javax.swing.JButton();
        btnHoaDon = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnKhachHang = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        lblDongHo = new javax.swing.JLabel();
        btnBanHang = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        pnmain.setBackground(new java.awt.Color(255, 255, 255));
        pnmain.setMaximumSize(new java.awt.Dimension(940, 580));
        pnmain.setLayout(new java.awt.BorderLayout());
        jPanel2.add(pnmain);
        pnmain.setBounds(140, 0, 950, 710);

        btnThoat.setText("Exit");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThoatMouseClicked(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });
        jPanel2.add(btnThoat);
        btnThoat.setBounds(0, 350, 140, 50);

        btnSanPham.setText("Sản Phẩm");
        btnSanPham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSanPhamMouseClicked(evt);
            }
        });
        jPanel2.add(btnSanPham);
        btnSanPham.setBounds(0, 50, 140, 50);

        btnKhuyenMai.setText("Khuyến Mãi");
        btnKhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhuyenMaiMouseClicked(evt);
            }
        });
        btnKhuyenMai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhuyenMaiActionPerformed(evt);
            }
        });
        jPanel2.add(btnKhuyenMai);
        btnKhuyenMai.setBounds(0, 100, 140, 50);

        btnHoaDon.setText("Hóa Đơn");
        btnHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHoaDonMouseClicked(evt);
            }
        });
        jPanel2.add(btnHoaDon);
        btnHoaDon.setBounds(0, 150, 140, 50);

        btnThongKe.setText("Thống Kê");
        btnThongKe.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongKeMouseClicked(evt);
            }
        });
        jPanel2.add(btnThongKe);
        btnThongKe.setBounds(0, 200, 140, 50);

        btnKhachHang.setText("Khách Hàng");
        btnKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhachHangMouseClicked(evt);
            }
        });
        jPanel2.add(btnKhachHang);
        btnKhachHang.setBounds(0, 250, 140, 50);

        btnNhanVien.setText("Nhân Viên");
        btnNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhanVienMouseClicked(evt);
            }
        });
        btnNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanVienActionPerformed(evt);
            }
        });
        jPanel2.add(btnNhanVien);
        btnNhanVien.setBounds(0, 300, 140, 50);

        lblDongHo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblDongHo.setForeground(new java.awt.Color(255, 51, 51));
        lblDongHo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Alarm.png"))); // NOI18N
        lblDongHo.setText("00:00:00 PM");
        jPanel2.add(lblDongHo);
        lblDongHo.setBounds(10, 570, 110, 30);

        btnBanHang.setText("Bán Hàng");
        btnBanHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBanHangMouseClicked(evt);
            }
        });
        btnBanHang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanHangActionPerformed(evt);
            }
        });
        jPanel2.add(btnBanHang);
        btnBanHang.setBounds(0, 0, 140, 50);

        jLabel2.setText("Chức vụ:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(10, 530, 60, 20);
        jPanel2.add(lblName);
        lblName.setBounds(60, 500, 80, 21);

        jLabel4.setText("Xin chào:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(10, 500, 60, 16);
        jPanel2.add(lblChucVu);
        lblChucVu.setBounds(60, 530, 80, 21);

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 1090, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKhuyenMaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhuyenMaiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKhuyenMaiActionPerformed

    private void btnNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanVienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhanVienActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnSanPhamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanPhamMouseClicked
        // TODO add your handling code here:
        setpanel(new SanPham());
        JButton[] btn1= {btnBanHang,btnThoat,btnHoaDon,btnKhachHang,btnNhanVien,btnThongKe,btnKhuyenMai};
        JButton[] btn2= {btnSanPham};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(255, 144, 1));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(255, 144, 1));
        }
    }//GEN-LAST:event_btnSanPhamMouseClicked

    private void btnBanHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanHangMouseClicked
      
        setpanel(new BanHang());
        JButton[] btn1= {btnSanPham,btnThoat,btnHoaDon,btnKhachHang,btnNhanVien,btnThongKe,btnKhuyenMai};
        JButton[] btn2= {btnBanHang};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(255, 144, 1));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(255, 144, 1));
        }
    }//GEN-LAST:event_btnBanHangMouseClicked

    private void btnKhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhuyenMaiMouseClicked
        // TODO add your handling code here:
        setpanel(new KhuyenMai());
        JButton[] btn1= {btnBanHang,btnThoat,btnHoaDon,btnKhachHang,btnNhanVien,btnThongKe,btnSanPham};
        JButton[] btn2= {btnKhuyenMai};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(255, 144, 1));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(255, 144, 1));
        }
    }//GEN-LAST:event_btnKhuyenMaiMouseClicked

    private void btnHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoaDonMouseClicked
        // TODO add your handling code here:
        setpanel(new HoaDonChiTiet());
        JButton[] btn1= {btnBanHang,btnThoat,btnSanPham,btnKhachHang,btnNhanVien,btnThongKe,btnKhuyenMai};
        JButton[] btn2= {btnHoaDon};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(255, 144, 1));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(255, 144, 1));
        }
    }//GEN-LAST:event_btnHoaDonMouseClicked

    private void btnThongKeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongKeMouseClicked
        // TODO add your handling code here:
        setpanel(new ThongKe());
        JButton[] btn1= {btnBanHang,btnThoat,btnHoaDon,btnKhachHang,btnNhanVien,btnSanPham,btnKhuyenMai};
        JButton[] btn2= {btnThongKe};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(255, 144, 1));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(255, 144, 1));
        }
    }//GEN-LAST:event_btnThongKeMouseClicked

    private void btnKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachHangMouseClicked
        // TODO add your handling code here:
        setpanel(new KhachHang());
        JButton[] btn1= {btnBanHang,btnThoat,btnHoaDon,btnSanPham,btnNhanVien,btnThongKe,btnKhuyenMai};
        JButton[] btn2= {btnKhachHang};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(255, 144, 1));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(255, 144, 1));
        }
    }//GEN-LAST:event_btnKhachHangMouseClicked

    private void btnNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanVienMouseClicked
        // TODO add your handling code here:
        setpanel(new NhanVien());
        JButton[] btn1= {btnBanHang,btnThoat,btnHoaDon,btnKhachHang,btnSanPham,btnThongKe,btnKhuyenMai};
        JButton[] btn2= {btnNhanVien};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(255, 144, 1));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(255, 144, 1));
        }
    }//GEN-LAST:event_btnNhanVienMouseClicked

    private void btnThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseClicked
        // TODO add your handling code here:
        JButton[] btn1= {btnBanHang,btnSanPham,btnHoaDon,btnKhachHang,btnNhanVien,btnThongKe,btnKhuyenMai};
        JButton[] btn2= {btnThoat};
        for (JButton btn22 : btn2) {
            btn22.setBackground(new Color(255, 144, 1));
        }
        for (JButton btn11 : btn1) {
            btn11.setBackground(new Color(255, 144, 1));
        }
        setVisible(false);
    }//GEN-LAST:event_btnThoatMouseClicked

    private void btnBanHangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanHangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBanHangActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewQuanLy.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewQuanLy().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanHang;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKhachHang;
    private javax.swing.JButton btnKhuyenMai;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnSanPham;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblDongHo;
    private javax.swing.JLabel lblName;
    private javax.swing.JPanel pnmain;
    // End of variables declaration//GEN-END:variables
}
